samba_users:
  - name: lfcarrega
    password: "{{ lfcarrega_smb_password }}"
  - name: brcarrega
    password: "{{ brcarrega_smb_password }}"

samba_shares:
  - name: storage
    path: /srv/storage
    comment: "Storage"
    browseable: yes
    read_only: no

storage_acl_bases:
  - /srv/storage/hdd
  - /srv/storage/ssd

storage_personal_dirs:
  - user: lfcarrega
    paths:
      - /srv/storage/hdd/lfcarrega
      - /srv/storage/ssd/lfcarrega
  - user: brcarrega
    paths:
      - /srv/storage/hdd/brcarrega
      - /srv/storage/ssd/brcarrega

storage_shared_dirs:
  - /srv/storage/hdd/shared
  - /srv/storage/ssd/shared
